title:              WentaoL
tagline:            Study and life
description:        Life is a struggle
url:                http://YourName.github.io

author:
  name:             Your Name
  url:              https://twitter.com/YourName
  email:            YourName@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
